version: "3"
services:
  app:
    image: f0junior/nodejs:latest
    container_name: frontend-react
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./public
        target: /www/public
      - type: bind
        source: ./src
        target: /www/src
