version: "3.7"
services:
  db:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=q1w2e3
      - MYSQL_DATABASE=crud
  admindb:
    image: phpmyadmin:latest
    container_name: admindb
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
  backend:
    build: 
      dockerfile: ./API/Dockerfile
      context: .
    image: f0junior/php
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./API
        target: /crud
    depends_on:
      - db
    links:
      - db:database
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    image: f0junior/react
    container_name: frontend
    ports: 
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /crud
